FROM golang:1.25.6 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/othela ./cmd/othela

FROM debian:bookworm-slim

WORKDIR /app
COPY --from=builder /app/othela .

# Expose the API port
EXPOSE 8080

CMD ["./othela"]