services:
  othela:
    build:
      context: .
      dockerfile: Dockerfile.othela
    image: helvilette-othela:local
    ports:
      - "8080:8080"
    volumes:
      - ./helvillette/othela/data:/app/helvillette/othela/data
    networks:
      - helvilette-net
    command: ["./othela", "--port=8080", "--data-dir=helvillette/othela/data/playbooks", "--log-level=info"]
    restart: unless-stopped

  node-1:
    build:
      context: .
      dockerfile: Dockerfile.agent
    image: helvilette-agent:local
    command: ["./agent", "--config=/var/lib/helvilette/agent.yaml"]
    volumes:
      - ./data/agent-1:/tmp/helvilette
      - ./data/configs/agent-01.yaml:/var/lib/helvilette/agent.yaml
    networks:
      - helvilette-net
    depends_on:
      - othela
    restart: unless-stopped

  node-2:
    build:
      context: .
      dockerfile: Dockerfile.agent
    image: helvilette-agent:local
    command: ["./agent", "--config=/var/lib/helvilette/agent.yaml"]
    volumes:
      - ./data/agent-2:/tmp/helvilette
      - ./data/configs/agent-02.yaml:/var/lib/helvilette/agent.yaml
    networks:
      - helvilette-net
    depends_on:
      - othela
    restart: unless-stopped

  node-3:
    build:
      context: .
      dockerfile: Dockerfile.agent
    image: helvilette-agent:local
    command: ["./agent", "--config=/var/lib/helvilette/agent.yaml"]
    volumes:
      - ./data/agent-3:/tmp/helvilette
      - ./data/configs/agent-03.yaml:/var/lib/helvilette/agent.yaml
    networks:
      - helvilette-net
    depends_on:
      - othela
    restart: unless-stopped

networks:
  helvilette-net:
    driver: bridge